ALTER TABLE [dbo].[AdminUserToRole]
    ADD CONSTRAINT [PK_AdminUserToRole] PRIMARY KEY CLUSTERED ([MemberID] ASC, [RoleID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

